# Generated by Django 4.2.11 on 2024-03-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_completed',
        ),
    ]
